global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastify-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels: 
          environment: 'development'
          region: 'in-west'